In [24]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.DataFrame([[23,20000,1],[25,50000,2],[27,70000,3],[29,75000,4],[30,80000,5]],columns=['age','sal','price in lac'])

In [25]:
x = df[['age','sal']]
y = df['price in lac']


In [26]:
x_train,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [27]:
x_train

age    sal
4   30  80000
2   27  70000
0   23  20000
3   29  75000

In [28]:
import numpy as np
arr = np.array([[23,20000],[25,50000],[27,70000],[29,75000],[30,80000]])
arr

array([[   23, 20000],
       [   25, 50000],
       [   27, 70000],
       [   29, 75000],
       [   30, 80000]])

In [37]:
scaler = StandardScaler(copy=False)
res = scaler.fit_transform(x_train)
print(res)
scaler.mean_

[[ 1.02575529  0.7787612 ]
 [-0.09325048  0.36342189]
 [-1.58525817 -1.71327463]
 [ 0.65275337  0.57109154]]


array([2.725e+01, 6.125e+04])

In [38]:
scaler.scale_

array([2.68095132e+00, 2.40767004e+04])

In [36]:
x_train

age    sal
4   30  80000
2   27  70000
0   23  20000
3   29  75000

In [35]:
scaler = StandardScaler(with_mean=False,with_std=False)
res = scaler.fit_transform(x_train)
print(res)

[[3.0e+01 8.0e+04]
 [2.7e+01 7.0e+04]
 [2.3e+01 2.0e+04]
 [2.9e+01 7.5e+04]]


In [40]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
print(x_train_scaled)

[[ 1.02575529  0.7787612 ]
 [-0.09325048  0.36342189]
 [-1.58525817 -1.71327463]
 [ 0.65275337  0.57109154]]


In [41]:
xtest

age    sal
1   25  50000

In [42]:
scaler.transform(xtest)

array([[-0.83925433, -0.46725672]])

In [43]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.DataFrame([[23,20000,1],[25,50000,2],[27,70000,3],[29,75000,4],[30,80000,5]],columns=['age','sal','price in lac'])

In [44]:
x = df[['age','sal']]
y = df['price in lac']


In [45]:
x_train,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [46]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
print(x_train_scaled)

[[ 1.02575529  0.7787612 ]
 [-0.09325048  0.36342189]
 [-1.58525817 -1.71327463]
 [ 0.65275337  0.57109154]]


In [47]:
scaler.transform(xtest)

array([[-0.83925433, -0.46725672]])

In [48]:
scaler.mean_

array([2.725e+01, 6.125e+04])

In [49]:
scaler.scale_

array([2.68095132e+00, 2.40767004e+04])

In [ ]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train['age'])
''' 
x_train_scaled = scaler.fit_transform(x_train['age'])
ValueError: Expected a 2-dimensional container 
but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) 
or a single column (i.e. single feature) instead.

'''
print(x_train_scaled)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.