In [205]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [206]:
df_sd = pd.read_csv('standardscaler.csv')

In [207]:
df_sd

Feature1  Feature2      Feature3         Target
0           7    506815  78179.054805  147107.322662
1           4    293822  70538.588873  127684.231772
2           8     77218  44636.920014   87982.249559
3           5    588518  86421.631346  166046.587018
4           7    771044  55814.069145  101011.603738
..        ...       ...           ...            ...
995         8    318348  38587.511702   68752.511537
996         1    183958  79172.046754  144130.196824
997         9    990156  59598.924619  103252.136934
998         7    278707  10126.081336   22002.231220
999         3     93324  84713.964255  150272.089596

[1000 rows x 4 columns]

In [208]:
df_sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Feature1  1000 non-null   int64  
 1   Feature2  1000 non-null   int64  
 2   Feature3  1000 non-null   float64
 3   Target    1000 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 31.4 KB


In [209]:
X = df_sd.drop('Target',axis=1)
y = df_sd['Target']

In [210]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)

## Without Using StandardScaler()

In [211]:
#model_creation
model = LinearRegression()

In [212]:
#fit /train the model
model.fit(xtrain,ytrain)

LinearRegression()

In [213]:
test_score = model.score(xtest,ytest)
print(f"Test score : {test_score}")

Test score : 0.9902822563064014


In [214]:
train_score = model.score(xtrain,ytrain)
print(f"Train score : {train_score}")

Train score : 0.990280886960456


## With Using StandardScaler()

In [215]:
#creating object for StandardScaler() to access fit_transform,transform

scaler = StandardScaler()

In [216]:

xtrain_scaled = scaler.fit_transform(xtrain) #learn and tranform the values for the model training
xtest_scaled = scaler.transform(xtest) #just transform the values for model testing


In [217]:
model = LinearRegression() #model creation

In [218]:
model.fit(xtrain_scaled,ytrain) #model fit/train

LinearRegression()

In [219]:
#evaluation for test
test_score = model.score(xtest_scaled,ytest)
print(f"Test score : {test_score}")

Test score : 0.9902822563064014


In [220]:
#evaluation for train
train_score = model.score(xtrain_scaled,ytrain)
print(f"Train score : {train_score}")

Train score : 0.990280886960456


In [221]:
print('''Without StandardScaler Model Performance \nTrain score : 0.990280886960456\nTest score : 0.9902822563064014''')


Without StandardScaler Model Performance 
Train score : 0.990280886960456
Test score : 0.9902822563064014


In [222]:
print('''With StandardScaler Model Performance
Train score : 0.990280886960456
Test score : 0.9902822563064014''')

With StandardScaler Model Performance
Train score : 0.990280886960456
Test score : 0.9902822563064014


In [223]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
# scaler.fit_transform()

In [224]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [225]:
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Blue"],
    "Size": ["Small", "Medium", "Large", "Small", "Large"],
    "Level": ["Low", "Medium", "High", "Medium", "Low"],
    "City": ["Chennai", "Delhi", "Mumbai", "Delhi", "Chennai"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes"]
})

In [226]:
df

Color    Size   Level     City Purchased
0    Red   Small     Low  Chennai       Yes
1   Blue  Medium  Medium    Delhi        No
2  Green   Large    High   Mumbai       Yes
3    Red   Small  Medium    Delhi        No
4   Blue   Large     Low  Chennai       Yes

In [227]:
label_encoder = LabelEncoder()

label_encoder.fit_transform(df['Purchased'])


array([1, 0, 1, 0, 1])

In [228]:
'''.
label_encoder.fit_transform(df[['Purchased','City']])
ValueError: y should be a 1d array, got an array of shape (5, 2) instead.
'''

".\nlabel_encoder.fit_transform(df[['Purchased','City']])\nValueError: y should be a 1d array, got an array of shape (5, 2) instead.\n"

In [229]:
label_encoder.fit_transform(df[['Purchased']])


c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 0, 1])

In [230]:
res = df[['Purchased']]

In [231]:
res.shape

(5, 1)

In [232]:
'''.
label_encoder.transform([['Yes','Yes']])
ValueError: y should be a 1d array, got an array of shape (1, 2) instead.

'''

".\nlabel_encoder.transform([['Yes','Yes']])\nValueError: y should be a 1d array, got an array of shape (1, 2) instead.\n\n"

In [233]:
'''.
label_encoder.transform(['Yess'])
ValueError: y contains previously unseen labels: 'Yess'
'''


".\nlabel_encoder.transform(['Yess'])\nValueError: y contains previously unseen labels: 'Yess'\n"

In [234]:
df

Color    Size   Level     City Purchased
0    Red   Small     Low  Chennai       Yes
1   Blue  Medium  Medium    Delhi        No
2  Green   Large    High   Mumbai       Yes
3    Red   Small  Medium    Delhi        No
4   Blue   Large     Low  Chennai       Yes

In [235]:
one_hot_encoder = OneHotEncoder()
''' 
one_hot_encoder.fit_transform(df['Color'])
ValueError: Expected a 2-dimensional container 
but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or 
a single column (i.e. single feature) instead.

'''

" \none_hot_encoder.fit_transform(df['Color'])\nValueError: Expected a 2-dimensional container \nbut got <class 'pandas.core.series.Series'> instead. \nPass a DataFrame containing a single row (i.e. single sample) or \na single column (i.e. single feature) instead.\n\n"

In [236]:
res = one_hot_encoder.fit_transform(df[['Color','City']])

In [237]:
res

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (5, 6)>

In [238]:
res.toarray()

array([[0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.]])

In [239]:
res_cols = one_hot_encoder.get_feature_names_out()

In [240]:
res_cols

array(['Color_Blue', 'Color_Green', 'Color_Red', 'City_Chennai',
       'City_Delhi', 'City_Mumbai'], dtype=object)

In [241]:
res = res.toarray()

In [242]:
res

array([[0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.]])

In [243]:
df['Color'].unique()

array(['Red', 'Blue', 'Green'], dtype=object)

In [244]:
pd.DataFrame(res,columns=res_cols)

Color_Blue  Color_Green  Color_Red  City_Chennai  City_Delhi  City_Mumbai
0         0.0          0.0        1.0           1.0         0.0          0.0
1         1.0          0.0        0.0           0.0         1.0          0.0
2         0.0          1.0        0.0           0.0         0.0          1.0
3         0.0          0.0        1.0           0.0         1.0          0.0
4         1.0          0.0        0.0           1.0         0.0          0.0

In [245]:
one_hot_encoder = OneHotEncoder(sparse_output=False,dtype='int')

In [246]:
res = one_hot_encoder.fit_transform(df[['Color','City']])

In [247]:
# ress

In [248]:
one_hot_encoder.fit_transform(df[['Color','City']])


array([[0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 0]])

In [249]:

'''.
one_hot_encoder.fit(df[['Color','City']])

one_hot_encoder.transform(df[['Color']])
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- City
'''

".\none_hot_encoder.fit(df[['Color','City']])\n\none_hot_encoder.transform(df[['Color']])\nValueError: The feature names should match those that were passed during fit.\nFeature names seen at fit time, yet now missing:\n- City\n"

In [250]:
'''.
one_hot_encoder.fit_transform(df[['Color','City']])
one_hot_encoder.transform([['Red']])
ValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.

'''

".\none_hot_encoder.fit_transform(df[['Color','City']])\none_hot_encoder.transform([['Red']])\nValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.\n\n"

In [251]:
one_hot_encoder.get_feature_names_out()

array(['Color_Blue', 'Color_Green', 'Color_Red', 'City_Chennai',
       'City_Delhi', 'City_Mumbai'], dtype=object)

In [252]:
one_hot_encoder.transform([['Red','Chennai']])
# array([[0, 0, 1, 1, 0, 0]])


c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0, 0, 1, 1, 0, 0]])

In [253]:
'''.
one_hot_encoder.transform([['Redd','Chennai']])
ValueError: Found unknown categories ['Redd'] in column 0 during transform

'''
# array([[0, 0, 1, 1, 0, 0]])


".\none_hot_encoder.transform([['Redd','Chennai']])\nValueError: Found unknown categories ['Redd'] in column 0 during transform\n\n"

In [254]:
one_hot_encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

In [255]:
one_hot_encoder.fit_transform(df[['Color']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [256]:
# one_hot_encoder.transform([['Red','Red']])

In [257]:
one_hot_encoder.transform([['Redd'],['Red']])


c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0.],
       [0., 0., 1.]])

In [258]:
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Blue"],
    "Size": ["Small", "Medium", "Large", "Small", "Large"],
    "Level": ["Low", "Medium", "High", "Medium", "Low"],
    "City": ["Chennai", "Delhi", "Mumbai", "Delhi", "Chennai"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes"]
})

In [259]:
df

Color    Size   Level     City Purchased
0    Red   Small     Low  Chennai       Yes
1   Blue  Medium  Medium    Delhi        No
2  Green   Large    High   Mumbai       Yes
3    Red   Small  Medium    Delhi        No
4   Blue   Large     Low  Chennai       Yes

In [260]:
#OrdinalEncoder()
from sklearn.preprocessing import OrdinalEncoder

In [261]:
encode = OrdinalEncoder()

values = encode.fit_transform(df[['Color']])

In [262]:
df

Color    Size   Level     City Purchased
0    Red   Small     Low  Chennai       Yes
1   Blue  Medium  Medium    Delhi        No
2  Green   Large    High   Mumbai       Yes
3    Red   Small  Medium    Delhi        No
4   Blue   Large     Low  Chennai       Yes

Red-> 2
Blue -> 0
Green -> 1

In [263]:
values

array([[2.],
       [0.],
       [1.],
       [2.],
       [0.]])

In [274]:
values
'''.
encode = OrdinalEncoder(categories=[['Small','Medium','Large']])
values = encode.fit_transform(df[['Color']])
ValueError: Found unknown categories ['Green', 'Red', 'Blue'] in column 0 during fit
'''

".\nencode = OrdinalEncoder(categories=[['Small','Medium','Large']])\nvalues = encode.fit_transform(df[['Color']])\nValueError: Found unknown categories ['Green', 'Red', 'Blue'] in column 0 during fit\n"

In [272]:
encode = OrdinalEncoder(categories=[['Small','Medium','Large'],['Blue','Green','Red'],['Low','Medium','High'],['Chennai','Delhi','Mumbai'],['Yes','No']])
values = encode.fit_transform(df)
values

ValueError: Found unknown categories ['Green', 'Red', 'Blue'] in column 0 during fit

In [275]:
encode = OrdinalEncoder(categories=[['Blue','Green','Red'],['Small','Medium','Large'],['Low','Medium','High'],['Chennai','Delhi','Mumbai'],['Yes','No']])
values = encode.fit_transform(df)
values

array([[2., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1.],
       [1., 2., 2., 2., 0.],
       [2., 0., 1., 1., 1.],
       [0., 2., 0., 0., 0.]])

In [277]:
'''.
encode = OrdinalEncoder(categories=[['Blue','Green','Red'],['Small','Medium','Large'],
['Low','Medium','High'],['Chennai','Delhi','Mumbai'],['Yes','No']])
values = encode.fit_transform(df)
encode.transform([['Red']])
ValueError: X has 1 features, but OrdinalEncoder is expecting 5 features as input.

'''

".\nencode = OrdinalEncoder(categories=[['Blue','Green','Red'],['Small','Medium','Large'],\n['Low','Medium','High'],['Chennai','Delhi','Mumbai'],['Yes','No']])\nvalues = encode.fit_transform(df)\nencode.transform([['Red']])\nValueError: X has 1 features, but OrdinalEncoder is expecting 5 features as input.\n\n"

In [ ]:
encode.transform([['Red','Small','Low','Chennai','Yes']])

c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2., 0., 0., 0., 0.]])

In [281]:
encode = OrdinalEncoder(categories=[['Blue','Green','Red']])
values = encode.fit_transform(df[['Color']])
values

array([[2.],
       [0.],
       [1.],
       [2.],
       [0.]])

In [283]:
'''.
encode = OrdinalEncoder(categories=[['Blue','Green','Red']])
values = encode.fit_transform(df[['Color']])
encode.transform([['Orange']])
ValueError: Found unknown categories ['Orange'] in column 0 during transform
'''

".\nencode = OrdinalEncoder(categories=[['Blue','Green','Red']])\nvalues = encode.fit_transform(df[['Color']])\nencode.transform([['Orange']])\nValueError: Found unknown categories ['Orange'] in column 0 during transform\n"

In [ ]:
'''.
encode = OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value",
unknown_value=0)
values = encode.fit_transform(df[['Color']])
encode.transform([['Orange']])
ValueError: The used value for unknown_value 0 is 
one of the values already used for encoding the seen categories.
'''


'.\nencode = OrdinalEncoder(categories=[[\'Blue\',\'Green\',\'Red\']],handle_unknown="use_encoded_value",\nunknown_value=0)\nvalues = encode.fit_transform(df[[\'Color\']])\nencode.transform([[\'Orange\']])\nValueError: The used value for unknown_value 0 is \none of the values already used for encoding the seen categories.\n\n'

In [290]:
'''.
encode = OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value")
values = encode.fit_transform(df[['Color']])
encode.transform([['Orange']])
TypeError: unknown_value should be an integer or 
np.nan when handle_unknown is 'use_encoded_value', got None.
'''


'.\nencode = OrdinalEncoder(categories=[[\'Blue\',\'Green\',\'Red\']],handle_unknown="use_encoded_value")\nvalues = encode.fit_transform(df[[\'Color\']])\nencode.transform([[\'Orange\']])\nTypeError: unknown_value should be an integer or \nnp.nan when handle_unknown is \'use_encoded_value\', got None.\n'

In [ ]:
#How to handle unknown values ⬇️⬇️⬇️
encode = OrdinalEncoder(categories=[['Blue','Green','Red']],handle_unknown="use_encoded_value",unknown_value=-1)
values = encode.fit_transform(df[['Color']])
encode.transform([['Orange']]) #returns -1

c:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[-1.]])